### ISSUE TITLE
MiniLogger is not thread-safe

### ISSUE THREAD

**Issue by cossio** [JuliaLogging/MiniLoggers.jl#30]
These lines:

https://github.com/JuliaLogging/MiniLoggers.jl/blob/d113b9a176479e09d925e14aed418a97401cb25b/src/minilogger.jl#L215-L219

suffer from same issue as: https://github.com/JuliaLang/julia/issues/34600.

**Comment by cossio** [comment]
Would a PR wrapping `message_limits` with a lock help?

**Comment by Arkoniak** [comment]
Yeah, it's a good catch. I have never used `maxlog` so never experienced this issue, but you are correct.
`lock` looks as a good solution, if it is used inside `if` condition.

Can you make a PR?

**Comment by Arkoniak** [comment]
Yes, I think it should be a field on `MiniLogger`. Alternatively, we can turn `message_limits` into thread-safe structure. Something like this (it's just a skeleton, I may have missed something)

```julia
struct ThreadSafeDict{K, V}
  dict::Dict{K, V}
  lock::ReentrantLock
end

ThreadSafeDict(dict) = ThreadSafeDict(dict, ReentrantLock())
Base.get(d::ThreadSafeDict, k, def) = get(d.dict, k, def)

function remain(d::ThreadSafeDict, )
  lock(d.lock)
  remaining = get!(d.dict, id, maxlog)
  d.dict[id] = remaining - 1
  unlock(d.lock)
  
  return remaining
end
```

**Comment by cossio** [comment]
That's nice. I wrote a PR before reading your last comment. Let me know what you prefer.

**Comment by Arkoniak** [comment]
I like your version too, we can leave `ThreadSafeDict` structure for the future if need arise.

**Comment by cossio** [comment]
Hopefully at some point `Base.Dict` is thread-safe, perhaps using some variant of `ThreadSafeDict` ...
