### ISSUE TITLE
Space handling in kwargs output

### ISSUE THREAD

**Issue by Arkoniak** [JuliaLogging/MiniLoggers.jl#33]
As it was mentioned in https://github.com/JuliaLogging/MiniLoggers.jl/issues/19#issuecomment-1117098985 by default logger does not print space between message and keyword arguments:
```julia
julia> with_logger(MiniLogger()) do
       @info "hello" x=4 y=2
       end
[2022-04-29 10:55:19] Info: hellox = 4, y = 2
```

Relevant piece of code is: https://github.com/JuliaLogging/MiniLoggers.jl/blob/master/src/minilogger.jl#L242-L253

Proper behavior should be:
```julia
julia> with_logger(MiniLogger()) do
       @info "hello" x=4 y=2
       end
[2022-04-29 10:55:19] Info: hello x = 4, y = 2
```

Additional test cases:
There should be no extra space when there are no keywords present:
```julia
julia> with_logger(MiniLogger()) do
       @info "hello"
       end
[2022-04-29 10:55:19] Info: hello
```

And there should be no extra space when there is no text message:
```julia
julia> with_logger(MiniLogger()) do
       @info x=4 y=2
       end
[2022-04-29 10:55:19] Info: x = 4, y = 2
```

**Comment by Arkoniak** [comment]
Unfortunately it is impossible to generate last test case, due to the way, how Julia prepares `message`. It can be seen in default logger too

```julia
julia> @info x = 3 y = 1
┌ Info: 3
└   y = 1
```

First argument always stripped to it's value and considered as message itself. Only way to overcome it, that I can find now, is to add empty string at the beginning of the log string
```julia
julia> @info "" x = 3 y = 1
┌ Info:
│   x = 3
└   y = 1
```
or the same in MiniLoggers.jl
```julia
julia> with_logger(MiniLogger()) do
       @info "" x=4 y=2
       end
[2022-04-29 10:55:19] Info: x = 4, y = 2
```

**Comment by cossio** [comment]
Thanks for handling this!
